# Generated by Django 3.1.6 on 2021-02-10 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Номер телефона')),
                ('video', models.FileField(null=True, upload_to='video/', verbose_name='Видео')),
                ('text', models.TextField(null=True, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='Block2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockIcon', models.FileField(null=True, upload_to='icons/', verbose_name='Иконка блока (в формате svg)')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Заголовок блока')),
                ('subtitle', models.CharField(max_length=255, null=True, verbose_name='Подзаголовок блока')),
                ('blockImage', models.FileField(null=True, upload_to='images/', verbose_name='Картинка в блоке (в формате svg)')),
            ],
        ),
        migrations.CreateModel(
            name='Block3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockIcon', models.FileField(null=True, upload_to='icons/', verbose_name='Иконка блока (в формате svg)')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Заголовок блока')),
                ('subtitle', models.CharField(max_length=255, null=True, verbose_name='Подзаголовок блока')),
                ('leftPercent', models.CharField(max_length=255, null=True, verbose_name='Проценты левый блок')),
                ('leftText', models.CharField(max_length=255, null=True, verbose_name='Текст левый блок')),
                ('centerPercent', models.CharField(max_length=255, null=True, verbose_name='Проценты центральный блок')),
                ('centerText', models.CharField(max_length=255, null=True, verbose_name='Текст центральный блок')),
                ('rightPercent', models.CharField(max_length=255, null=True, verbose_name='Проценты правый блок')),
                ('rightText', models.CharField(max_length=255, null=True, verbose_name='Текст правый блок')),
            ],
        ),
        migrations.CreateModel(
            name='Block4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockIcon', models.FileField(null=True, upload_to='icons/', verbose_name='Иконка блока (в формате svg)')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Заголовок блока')),
                ('subtitle', models.CharField(max_length=255, null=True, verbose_name='Подзаголовок блока')),
            ],
        ),
        migrations.CreateModel(
            name='Block5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Block6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Block7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supportBtnText', models.CharField(max_length=255, null=True, verbose_name='Текст на кнопке тех.поддержки')),
                ('supportBtnLink', models.CharField(max_length=255, null=True, verbose_name='Ссылка с  кнопки тех.поддержки')),
                ('innerBtn1Text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст на кнопке 1 меню')),
                ('innerBtn1Link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка с  кнопки 1 меню')),
                ('innerBtn2Text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст на кнопке 2 меню')),
                ('innerBtn2Link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка с  кнопки 2 меню')),
                ('innerBtn3Text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст на кнопке 3 меню')),
                ('innerBtn3Link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка с  кнопки 3 меню')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(null=True, upload_to='logo/', verbose_name='Логотип (в формате svg)')),
            ],
        ),
        migrations.CreateModel(
            name='Block4Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Заголовок элемента списка')),
                ('text', models.TextField(null=True, verbose_name='Текст элемента')),
                ('image', models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Видео')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/', verbose_name='Видео')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.block4')),
            ],
        ),
        migrations.CreateModel(
            name='Block2Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Заголовок элемента списка')),
                ('text', models.TextField(null=True, verbose_name='Текст элемента')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.block2')),
            ],
        ),
    ]
