# Generated by Django 3.1.6 on 2021-02-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210210_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block4features',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.block4'),
        ),
        migrations.AlterField(
            model_name='block4features',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
    ]
