# Generated by Django 3.1.6 on 2021-02-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210210_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='block5',
            name='blockIcon',
            field=models.FileField(null=True, upload_to='icons/', verbose_name='Иконка блока (в формате svg)'),
        ),
        migrations.AddField(
            model_name='block5',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='block5',
            name='subtitle',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок блока'),
        ),
        migrations.AddField(
            model_name='block5',
            name='text',
            field=models.TextField(max_length=255, null=True, verbose_name='Текст блока'),
        ),
        migrations.AddField(
            model_name='block5',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок блока'),
        ),
    ]
