# Generated by Django 3.1.6 on 2021-02-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210210_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='block5',
            name='subsubtitle',
            field=models.CharField(max_length=255, null=True, verbose_name='Подподзаголовок блока'),
        ),
    ]
