# Generated by Django 3.1.6 on 2021-03-08 09:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_block5_subsubtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='footer_contacts',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Реквизиты в футере'),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_soc1_icon',
            field=models.FileField(null=True, upload_to='icon/', verbose_name='Иконка соц сети 1'),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_soc1_link',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка соц сети 1'),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_soc2_icon',
            field=models.FileField(null=True, upload_to='icon/', verbose_name='Иконка соц сети 2'),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_soc2_link',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка соц сети 2'),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_soc3_icon',
            field=models.FileField(null=True, upload_to='icon/', verbose_name='Иконка соц сети 3'),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_soc3_link',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка соц сети 3'),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст под лого в футере'),
        ),
        migrations.AddField(
            model_name='settings',
            name='logo_footer',
            field=models.FileField(null=True, upload_to='logo/', verbose_name='Логотип футер (в формате svg)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.FileField(null=True, upload_to='logo/', verbose_name='Логотип хедер (в формате svg)'),
        ),
    ]
