# Generated by Django 3.1.6 on 2021-03-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210308_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='block2features',
            name='blockImage',
            field=models.FileField(null=True, upload_to='images/', verbose_name='Картинка в блоке '),
        ),
        migrations.AlterField(
            model_name='block2',
            name='blockIcon',
            field=models.FileField(null=True, upload_to='icons/', verbose_name='Иконка блока '),
        ),
        migrations.AlterField(
            model_name='block2',
            name='blockImage',
            field=models.FileField(null=True, upload_to='images/', verbose_name='Картинка в блоке '),
        ),
        migrations.AlterField(
            model_name='block3',
            name='blockIcon',
            field=models.FileField(null=True, upload_to='icons/', verbose_name='Иконка блока '),
        ),
        migrations.AlterField(
            model_name='block4',
            name='blockIcon',
            field=models.FileField(null=True, upload_to='icons/', verbose_name='Иконка блока '),
        ),
        migrations.AlterField(
            model_name='block5',
            name='blockIcon',
            field=models.FileField(null=True, upload_to='icons/', verbose_name='Иконка блока '),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.FileField(null=True, upload_to='logo/', verbose_name='Логотип хедер '),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo_footer',
            field=models.FileField(null=True, upload_to='logo/', verbose_name='Логотип футер '),
        ),
    ]
