# Generated by Django 3.1.6 on 2021-03-08 09:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210308_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='block6',
            name='blockIcon',
            field=models.FileField(null=True, upload_to='icons/', verbose_name='Иконка блока '),
        ),
        migrations.AddField(
            model_name='block6',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='block6',
            name='subsubtitle',
            field=models.CharField(max_length=255, null=True, verbose_name='Подподзаголовок блока'),
        ),
        migrations.AddField(
            model_name='block6',
            name='subtitle',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок блока'),
        ),
        migrations.AddField(
            model_name='block6',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст блока'),
        ),
        migrations.AddField(
            model_name='block6',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок блока'),
        ),
    ]
