# Generated by Django 3.1.6 on 2021-03-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210308_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='avatar',
            field=models.FileField(null=True, upload_to='icons/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='work',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
