# Generated by Django 3.1.6 on 2021-03-08 10:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210308_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст отзыва'),
        ),
    ]
