# Generated by Django 3.1.6 on 2021-03-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210308_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='link',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
