# Generated by Django 3.1.6 on 2021-03-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_settings_footer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='footer_company',
            field=models.CharField(max_length=255, null=True, verbose_name='Название организации'),
        ),
    ]
