# Generated by Django 3.1.6 on 2021-03-08 10:50

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210308_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название страницы')),
                ('name_slug', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Название решения')),
                ('header_btn_img', models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка на кнопке в меню')),
                ('header_btn_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст на кнопке в меню')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок страницы')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок страницы')),
                ('video', models.FileField(null=True, upload_to='page/', verbose_name='Видео под заголовком')),
                ('subsubtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст под видео')),
                ('video_block_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок видео блока')),
                ('video_block_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст видео блока')),
                ('video_block_video', models.FileField(null=True, upload_to='page/', verbose_name='Видео в видео блоке')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Страница отраслевого решения',
                'verbose_name_plural': 'Страницы отраслевых решений',
            },
        ),
        migrations.AlterField(
            model_name='header',
            name='supportBtnLink',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='header',
            name='supportBtnText',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст на ссылке'),
        ),
        migrations.CreateModel(
            name='PageFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(null=True, upload_to='images/', verbose_name='Иконка')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Заголовок элемента списка')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст элемента')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.page')),
            ],
        ),
        migrations.CreateModel(
            name='PageBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='images/', verbose_name='Картинка в блоке')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Заголовок элемента списка')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст элемента')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pages.page')),
            ],
        ),
    ]
