# Generated by Django 3.1.6 on 2021-03-08 11:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20210308_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageblocks',
            options={'verbose_name': 'Блок с картинкой', 'verbose_name_plural': 'Блоки с картинками'},
        ),
        migrations.AlterModelOptions(
            name='pagefeatures',
            options={'verbose_name': 'Приемущество', 'verbose_name_plural': 'Приемущества'},
        ),
        migrations.AlterField(
            model_name='page',
            name='header_btn_img',
            field=models.FileField(max_length=255, null=True, upload_to='', verbose_name='Картинка на кнопке в меню'),
        ),
        migrations.AlterField(
            model_name='page',
            name='header_btn_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст на кнопке в меню'),
        ),
        migrations.AlterField(
            model_name='page',
            name='subsubtitle',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст под видео'),
        ),
        migrations.AlterField(
            model_name='page',
            name='subtitle',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='video_block_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст видео блока'),
        ),
        migrations.AlterField(
            model_name='page',
            name='video_block_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок видео блока'),
        ),
        migrations.AlterField(
            model_name='pageblocks',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='pageblocks',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='pagefeatures',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='pagefeatures',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
