# Generated by Django 3.1.6 on 2021-03-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20210308_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='feedback_icon',
            field=models.FileField(null=True, upload_to='logo/', verbose_name='Иконка блока отзывы '),
        ),
        migrations.AddField(
            model_name='settings',
            name='feedback_subtitle',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок блока отзывы'),
        ),
        migrations.AddField(
            model_name='settings',
            name='feedback_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок блока отзывы'),
        ),
    ]
