# Generated by Django 3.1.6 on 2021-03-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20210308_1454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block7',
        ),
        migrations.AlterModelOptions(
            name='block1',
            options={'verbose_name': '2. Оффер', 'verbose_name_plural': '2. Оффер'},
        ),
        migrations.AlterModelOptions(
            name='block2',
            options={'verbose_name': '3. Управление', 'verbose_name_plural': '3. Управление'},
        ),
        migrations.AlterModelOptions(
            name='block2features',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блок'},
        ),
        migrations.AlterModelOptions(
            name='block3',
            options={'verbose_name': '4. Рост', 'verbose_name_plural': '4. Рост'},
        ),
        migrations.AlterModelOptions(
            name='block4',
            options={'verbose_name': '4. Инфо', 'verbose_name_plural': '4. Инфо'},
        ),
        migrations.AlterModelOptions(
            name='block4features',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блок'},
        ),
        migrations.AlterModelOptions(
            name='block5',
            options={'verbose_name': '5. Личный кабинет', 'verbose_name_plural': '5. Личный кабинет'},
        ),
        migrations.AlterModelOptions(
            name='block6',
            options={'verbose_name': '6. Возможности платформы', 'verbose_name_plural': '6. Возможности платформы'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': '1. Хедер', 'verbose_name_plural': '1. Хедер'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Общие блоки', 'verbose_name_plural': 'Общие блоки'},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='logo',
        ),
        migrations.AddField(
            model_name='header',
            name='logo',
            field=models.FileField(null=True, upload_to='logo/', verbose_name='Логотип хедер '),
        ),
    ]
