# Generated by Django 3.1.6 on 2021-03-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20210309_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название услуги')),
                ('image', models.FileField(max_length=255, null=True, upload_to='', verbose_name='Картинка на кнопке')),
                ('text', models.CharField(max_length=255, null=True, verbose_name='Текст на кнопке')),
                ('link', models.CharField(max_length=255, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуга',
            },
        ),
    ]
