# Generated by Django 3.1.6 on 2021-03-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20210309_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block4',
            options={'verbose_name': '5. Фунциональность', 'verbose_name_plural': '5. Фунциональность'},
        ),
        migrations.AlterModelOptions(
            name='block5',
            options={'verbose_name': '6. Личный кабинет', 'verbose_name_plural': '6. Личный кабинет'},
        ),
        migrations.AlterModelOptions(
            name='block6',
            options={'verbose_name': '7. Возможности платформы', 'verbose_name_plural': '7. Возможности платформы'},
        ),
        migrations.AlterModelOptions(
            name='block7',
            options={'verbose_name': '8. Стоимость', 'verbose_name_plural': '7. Стоимость'},
        ),
        migrations.RemoveField(
            model_name='block7',
            name='block3_subtitle',
        ),
        migrations.AddField(
            model_name='page',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Отображать видео блок'),
        ),
        migrations.AddField(
            model_name='page',
            name='video_block_image',
            field=models.FileField(blank=True, null=True, upload_to='page/', verbose_name='Картинка в видео блоке'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать страницу'),
        ),
        migrations.AlterField(
            model_name='page',
            name='video_block_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст видео блока'),
        ),
        migrations.AlterField(
            model_name='page',
            name='video_block_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок видео блока'),
        ),
        migrations.AlterField(
            model_name='page',
            name='video_block_video',
            field=models.FileField(blank=True, null=True, upload_to='page/', verbose_name='Видео в видео блоке'),
        ),
    ]
