# Generated by Django 3.1.6 on 2021-03-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20210310_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block7',
            options={'verbose_name': '8. Стоимость', 'verbose_name_plural': '8. Стоимость'},
        ),
        migrations.AddField(
            model_name='settings',
            name='implementation_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео на старнице внедрение '),
        ),
        migrations.AlterField(
            model_name='page',
            name='video_block_image',
            field=models.FileField(blank=True, null=True, upload_to='page/', verbose_name='Картинка в видео блоке (если видео файл выбран, картинка игнорируется)'),
        ),
    ]
