# Generated by Django 3.1.6 on 2021-04-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20210314_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block5',
            options={'verbose_name': '6. Возможности платформы', 'verbose_name_plural': '6. Возможности платформы'},
        ),
        migrations.AlterModelOptions(
            name='block6',
            options={'verbose_name': '7. Личный кабинет', 'verbose_name_plural': '7. Личный кабинет'},
        ),
        migrations.AlterField(
            model_name='page',
            name='video_block_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст видео блока'),
        ),
    ]
